### ISSUE TITLE
Create branch to hold code currently in master, but not intended for MVP release

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.image#14]
The initial code donation from Microsoft included more features than what we are targeting for MVP.  To simplify the repository and ease code review, @majguo  suggested we move the portions of the code that are not targeted for MVP to another branch.

This issue requests @git4rk  to create another branch, `service-integrations`, from `master` at the point in time right after the initial donation, and @majguo will make a PR that removes the irrelevant code from `master`.

**Comment by git4rk** [comment]
Created https://github.com/WASdev/azure.websphere-traditional.image/tree/service-integrations from commit level: https://github.com/WASdev/azure.websphere-traditional.image/commit/22a919a446d6c49fe6490ce75e4c3799466e2c8f

**Comment by majguo** [comment]
Hello @git4rk I confirmed with @edburns that the repo we recommend to create a new branch to accommodate the original donation code is repo https://github.com/WASdev/azure.websphere-traditional.cluster, instead of this one. Apologize for any inconvenience caused, but could you pls help again with:

- deleting `service-integrations` from repo https://github.com/WASdev/azure.websphere-traditional.image;
- and adding a new branch `service-integrations` into https://github.com/WASdev/azure.websphere-traditional.cluster, which contains the original donation code

Thanks.

**Comment by git4rk** [comment]
Deleted the branch from this repo.
